[[Qt6Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fee1217105cf0d1ba851d08dacebd96103608b0c"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "f488cf1046467e98988dc9ff05675d91686f54d5aa74f94decdc4f850131c797"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.0.3+1/Qt6Base.v6.0.3.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49b9fb7b8c457293d18828094acaeff288ca1350"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "83f534ccf0ae62f94d26a7c7a10dcfecf1939c59e6ec563ec9b65c50f9bde3e7"
    url = "https://github.com/barche/Qt6Base_jll.jl/releases/download/Qt6Base-v6.3.0+0/Qt6Base.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
git-tree-sha1 = "fdb2ca8be3998b785069212ccc95253a59f5436f"
os = "macos"

    [[Qt6Base.download]]
    sha256 = "8c1ff183014a6e3817a51a67288dbfa4e3b748d302eca9a3c851d8365919c65b"
    url = "https://github.com/barche/Qt6Base_jll.jl/releases/download/Qt6Base-v6.3.0+1/Qt6Base.v6.3.0.x86_64-apple-darwin.tar.gz"
[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2219db48e1382df6006b23b0ae93b83ff6cb18d8"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "e4d1727e6bef2c7157ae5974188265b7c32e00c9dbe5e106aa5e4ca303b40355"
    url = "https://github.com/barche/Qt6Base_jll.jl/releases/download/Qt6Base-v6.3.0+1/Qt6Base.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
